const express = require('express');
const router = express.Router();
const Conversation = require('../models/Conversation');

// Get all conversations
router.get('/', async (req, res) => {
    try {
        const { userId = 'anonymous' } = req.query;
        const conversations = await Conversation.find({ userId })
            .sort({ updatedAt: -1 })
            .select('_id preview isEmergency createdAt updatedAt messages');

        const formattedConversations = conversations.map(conv => ({
            id: conv._id,
            date: conv.updatedAt,
            preview: conv.preview,
            isEmergency: conv.isEmergency,
            messageCount: conv.messages.length,
            createdAt: conv.createdAt,
            updatedAt: conv.updatedAt
        }));

        res.json(formattedConversations);
    } catch (error) {
        console.error('Error fetching conversations:', error);
        res.status(500).json({ error: 'Failed to fetch conversations' });
    }
});

// Get a single conversation with all messages
router.get('/:id', async (req, res) => {
    try {
        const conversation = await Conversation.findById(req.params.id);
        if (!conversation) {
            return res.status(404).json({ error: 'Conversation not found' });
        }
        res.json(conversation);
    } catch (error) {
        console.error('Error fetching conversation:', error);
        res.status(500).json({ error: 'Failed to fetch conversation' });
    }
});

// Create a new conversation
router.post('/', async (req, res) => {
    try {
        const { userId = 'anonymous', messages, isEmergency = false } = req.body;

        const conversation = new Conversation({
            userId,
            messages,
            isEmergency,
            preview: '' // Will be auto-generated by the pre-save hook
        });

        await conversation.save();
        res.status(201).json(conversation);
    } catch (error) {
        console.error('Error creating conversation:', error);
        if (error.name === 'ValidationError') {
            const messages = Object.values(error.errors).map(val => val.message);
            console.error('Validation Errors:', messages);
            return res.status(400).json({ error: 'Validation Error', details: messages });
        }
        res.status(500).json({ error: 'Failed to create conversation', details: error.message });
    }
});

// Add a message to existing conversation
router.post('/:id/messages', async (req, res) => {
    try {
        const { role, content } = req.body;
        const conversation = await Conversation.findById(req.params.id);

        if (!conversation) {
            return res.status(404).json({ error: 'Conversation not found' });
        }

        conversation.messages.push({ role, content, timestamp: new Date() });
        await conversation.save();

        res.json(conversation);
    } catch (error) {
        console.error('Error adding message:', error);
        res.status(500).json({ error: 'Failed to add message' });
    }
});

// Delete a conversation
router.delete('/:id', async (req, res) => {
    try {
        const conversation = await Conversation.findByIdAndDelete(req.params.id);
        if (!conversation) {
            return res.status(404).json({ error: 'Conversation not found' });
        }
        res.json({ message: 'Conversation deleted successfully' });
    } catch (error) {
        console.error('Error deleting conversation:', error);
        res.status(500).json({ error: 'Failed to delete conversation' });
    }
});

// Delete all conversations for a user
router.delete('/', async (req, res) => {
    try {
        const { userId } = req.query;
        if (!userId) {
            return res.status(400).json({ error: 'UserId is required' });
        }
        const result = await Conversation.deleteMany({ userId });
        res.json({ message: 'All conversations deleted successfully', deletedCount: result.deletedCount });
    } catch (error) {
        console.error('Error deleting all conversations:', error);
        res.status(500).json({ error: 'Failed to delete conversations' });
    }
});

module.exports = router;
